const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare Report",
        description: "Create the weekly performance report.",
        date: "2025-11-20",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client Follow-Up",
        description: "Call and follow up with the client regarding updates.",
        date: "2025-11-18",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix Login Bug",
        description: "Resolve login issue on the website.",
        date: "2025-11-15",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Design UI",
        description: "Create UI mockups for dashboard.",
        date: "2025-11-22",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Attend team sync-up meeting.",
        date: "2025-11-19",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Database Cleanup",
        description: "Remove unused database entries.",
        date: "2025-11-17",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Write Documentation",
        description: "Create documentation for new feature.",
        date: "2025-11-16",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Security Check",
        description: "Run security tests on system.",
        date: "2025-11-21",
        category: "Security",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "API Testing",
        description: "Test all new API endpoints.",
        date: "2025-11-20",
        category: "Testing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Optimize Code",
        description: "Refactor slow modules.",
        date: "2025-11-18",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Inventory Check",
        description: "Update inventory list.",
        date: "2025-11-19",
        category: "Management",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Vendor Call",
        description: "Check availability with vendor.",
        date: "2025-11-18",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Payment Follow-Up",
        description: "Confirm payment with finance team.",
        date: "2025-11-15",
        category: "Finance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Event Planning",
        description: "Plan annual office event.",
        date: "2025-11-14",
        category: "Management",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Server Update",
        description: "Update server to latest version.",
        date: "2025-11-21",
        category: "IT",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Backup Files",
        description: "Backup company files to cloud.",
        date: "2025-11-19",
        category: "IT",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "System Monitoring",
        description: "Monitor RAM and CPU usage.",
        date: "2025-11-17",
        category: "Monitoring",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Training Session",
        description: "Take cybersecurity training.",
        date: "2025-11-16",
        category: "Training",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Ticket Handling",
        description: "Resolve pending support tickets.",
        date: "2025-11-15",
        category: "Support",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];
export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));

};
export const getLocalStorage = () => {
    const raw = JSON.parse(localStorage.getItem('employees'));
    const adminRaw = JSON.parse(localStorage.getItem('admin'));
    return {employess: raw, admin: adminRaw }
};
